### ISSUE TITLE
Destructors are not called when replacing a pinboards contents

### ISSUE THREAD

**Issue by cswindle** [bossmc/pinboard#7]
When storing data in a pinboard, if the contents are replaced, the old data does not have the destructors called, this leads to a memory leak.

I have attached a crate which demonstrates the issue, this can be verified by running valgrind against the example (using nightly-2017-07-06 as later versions seem to be broken).

[pinboard-test.zip](https://github.com/bossmc/pinboard/files/1489157/pinboard-test.zip)

**Comment by cswindle** [comment]
I have raised an issue to cover needing to run an old nightly version of rust: https://github.com/rust-lang/rust/issues/46138

**Comment by bossmc** [comment]
It seems this is due to the implementation of the underling crossbeam garbage collector.  The collector doesn't call destructors when garbage expires.  This is a deliberate design decision, though it's a little odd.

The way the crossbeam lock-free structures are implemented makes a couple of assumptions:

* Each stored item of data will be retrieved from the structure eventually
* Each stored item of data will only be retrieved once

This means that, for any `T` stored in the structure, they can assume that, when the entry is `unlink`ed that this is the one and only time that the data will be read, so they simply `ptr::read` the `T` out of the entry to get the `T` back for free.  The returned `T` will be dropped by the calling code (calling destructors) and the entry will be dropped (without calling destructors) when the garbage is collected.

In pinboard's case, the assumptions do not apply, data can be retrieved multiple times from a pinboard, and, when data is `unlink`ed, it is not returned to the caller (in fact, this second facet doesn't really change anything, the caller could never safely drop the returned `T` since it doesn't know when enough epochs have passed to ensure no-one else is trying to `clone()` it on another thread).

Calling the destructors in the garbage collector is simple, the issue is that it will lead to double frees in the crossbeam lock-free implementations.

**Comment by bossmc** [comment]
I've proposed a change to crossbeam to call destructors but it's incomplete and probably needs discussion.

https://github.com/crossbeam-rs/crossbeam/pull/158

**Comment by bossmc** [comment]
Fixed in #10 and released in `v2.0.0`.  Note that there's a new restriction on the stored value, that it has to be `'static` to ensure that no references outlive their referent while waiting for collection.
